### PR TITLE
Release `v4.0.0`

### PR DESCRIPTION
**Pull request by robbot006**
This is a draft of changelog for the `v4.0.0` release.
Here you can find all related translations changes: [v3.9.0...master](https://github.com/flarum-lang/french/compare/v3.9.0...master).

> ### ⚠️ Do not merge this pull request manually ⚠️
> 
> You should [approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request) this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release.

<details>
<summary>Show release notes preview</summary>

## v4.0.0

**General changes**:

* Removed outdated Flarum core translations (version `1.3` or higher is supported).

**Added support for new extensions**:

* [`blomstra/fontawesome`](https://github.com/blomstra/flarum-ext-fontawesome)
* [`blomstra/s3-assets`](https://extiverse.com/extension/blomstra/s3-assets)
* [`clarkwinkelmann/flarum-ext-discussion-bookmarks`](https://github.com/clarkwinkelmann/flarum-ext-discussion-bookmarks)
* [`clarkwinkelmann/flarum-ext-ipsum-autocomplete`](https://github.com/clarkwinkelmann/flarum-ext-ipsum-autocomplete)
* [`clarkwinkelmann/flarum-ext-selective-mediaembed`](https://github.com/clarkwinkelmann/flarum-ext-selective-mediaembed)
* [`datlechin/flarum-discussion-overview`](https://github.com/datlechin/flarum-discussion-overview)
* [`ianm/no-meta-title`](https://github.com/imorland/no-meta-title)
* [`justoverclock/best-answer-badge`](https://github.com/justoverclockl/best-answer-badge)
* [`tohsakarat/save-and-load-draft-automatically`](https://github.com/tohsakrat/save-and-load-draft-automatically)
* [`tohsakarat/tags-filter`](https://github.com/tohsakrat/flarum-tags-filter)

**Updated and/or removed outdated translations for extensions**:

* [`askvortsov/flarum-saml`](https://github.com/askvortsov1/flarum-saml)
* [`blomstra/flag-duplicates`](https://github.com/blomstra/flarum-ext-flag-duplicate)
* [`blomstra/payments`](https://extiverse.com/extension/blomstra/payments)
* [`blomstra/realtime`](https://extiverse.com/extension/blomstra/realtime)
* [`clarkwinkelmann/flarum-ext-scout`](https://github.com/clarkwinkelmann/flarum-ext-scout)
* [`datlechin/flarum-birthdays`](https://github.com/datlechin/flarum-birthdays)
* [`flarum/markdown`](https://github.com/flarum/markdown)
* [`flarum/statistics`](https://github.com/flarum/statistics)
* [`fof/analytics`](https://github.com/FriendsOfFlarum/analytics)
* [`fof/best-answer`](https://github.com/FriendsOfFlarum/best-answer)
* [`fof/byobu`](https://github.com/FriendsOfFlarum/byobu)
* [`fof/discussion-language`](https://github.com/FriendsOfFlarum/discussion-language)
* [`fof/filter`](https://github.com/FriendsOfFlarum/filter)
* [`fof/gamification`](https://github.com/FriendsOfFlarum/gamification)
* [`fof/merge-discussions`](https://github.com/FriendsOfFlarum/merge-discussions)
* [`fof/pretty-mail`](https://github.com/FriendsOfFlarum/pretty-mail)
* [`fof/sitemap`](https://github.com/FriendsOfFlarum/sitemap)
* [`fof/stopforumspam`](https://github.com/FriendsOfFlarum/stopforumspam)
* [`fof/subscribed`](https://github.com/FriendsOfFlarum/subscribed)
* [`fof/upload`](https://github.com/FriendsOfFlarum/upload)
* [`ianm/follow-users`](https://github.com/imorland/follow-users)
* [`ianm/level-ranks`](https://github.com/imorland/level-ranks)
* [`ianm/syndication`](https://github.com/imorland/syndication)
* [`ianm/synopsis`](https://github.com/imorland/synopsis)
* [`jslirola/flarum-ext-login2seeplus`](https://github.com/jslirola/flarum-ext-login2seeplus)
* [`justoverclock/discussion-info`](https://github.com/justoverclockl/discussions-info)
* [`justoverclock/last-registered-users`](https://github.com/justoverclockl/last-registered-users)
* [`justoverclock/related-discussions`](https://extiverse.com/extension/justoverclock/related-discussions)
* [`katosdev/signature`](https://github.com/katosdev/signature)
* [`kilowhat/flarum-ext-custom-paths`](https://extiverse.com/extension/kilowhat/flarum-ext-custom-paths)
* [`kilowhat/flarum-ext-rich-embeds`](https://extiverse.com/extension/kilowhat/flarum-ext-rich-embeds)
* [`michaelbelgium/mybb-to-flarum`](https://github.com/MichaelBelgium/mybb_to_flarum)
* [`michaelbelgium/flarum-profile-views`](https://github.com/MichaelBelgium/flarum-profile-views)
* [`migratetoflarum/fake-data`](https://github.com/migratetoflarum/fake-data)
* [`nearata/flarum-ext-embed-video`](https://github.com/Nearata/flarum-ext-embed-video)
* [`nearata/flarum-ext-minecraft-avatars`](https://github.com/Nearata/flarum-ext-minecraft-avatars)
* [`nearata/flarum-ext-tags-color-generator`](https://github.com/Nearata/flarum-ext-tags-color-generator)
* [`nearata/flarum-ext-twofactor`](https://github.com/Nearata/flarum-ext-twofactor)
* [`the-turk/flarum-mathren`](https://github.com/the-turk/flarum-mathren)
* [`the-turk/flarum-regrole`](https://github.com/the-turk/flarum-regrole)
* [`the-turk/flarum-stickiest`](https://github.com/the-turk/flarum-stickiest)
* [`therealsujitk/flarum-ext-gifs`](https://github.com/therealsujitk/flarum-ext-gifs)
* [`zerosonesfun/flarum-bbcode-button`](https://github.com/zerosonesfun/flarum-bbcode-button)

**Removed support for outdated extensions**:

* [`amaurycarrade/flarum-ext-syndication`](https://github.com/AmauryCarrade/flarum-ext-syndication)
* [`andre-pullinen/ads`](https://github.com/andre-pullinen/ads)
* [`antoinefr/flarum-ext-money`](https://github.com/AntoineFr/flarum-ext-money)
* [`antoinefr/flarum-ext-online`](https://github.com/AntoineFr/flarum-ext-online)
* [`askvortsov/flarum-auth-sync`](https://github.com/askvortsov1/flarum-auth-sync)
* [`clarkwinkelmann/flarum-ext-bookmarks`](https://github.com/clarkwinkelmann/flarum-ext-bookmarks)
* [`clarkwinkelmann/flarum-ext-email-as-display-name`](https://github.com/clarkwinkelmann/flarum-ext-email-as-display-name)
* [`clarkwinkelmann/flarum-ext-emojionearea`](https://github.com/clarkwinkelmann/flarum-ext-emojionearea)
* [`clarkwinkelmann/flarum-ext-manual-discussion-slug`](https://github.com/clarkwinkelmann/flarum-ext-manual-discussion-slug)
* [`clarkwinkelmann/flarum-ext-quiz-polls`](https://github.com/clarkwinkelmann/flarum-ext-quiz-polls)
* [`datitisev/flarum-ext-dashboard`](https://github.com/datitisev/flarum-ext-dashboard)
* `flarumi-oauth-vkontakte`
* `flarumi-oauth-yandex`
* [`fof/transliterator`](https://github.com/FriendsOfFlarum/transliterator)
* [`ianm/flarum-diff`](https://github.com/imorland/flarum-diff)
* [`ianm/flarum-regrole`](https://github.com/imorland/flarum-regrole)
* `justoverclock-discussion-sentiment-analyzer`
* [`justoverclock/image-gallery`](https://github.com/justoverclockl/image-gallery)
* [`justoverclock/flarum-ext-readmore`](https://github.com/justoverclockl/flarum-ext-readmore)
* [`kilowhat/flarum-ext-formulaire`](https://extiverse.com/extension/kilowhat/flarum-ext-formulaire)
* [`kvothe/reply-to-see`](https://github.com/oaklinq/flarum-ext-reply2see)
* [`kyrne/aegis`](https://extiverse.com/extension/kyrne/aegis)
* [`kyrne/shout`](https://github.com/KyrneDev/Shout-public)
* [`luuhai48/oauth-google`](https://github.com/luuhai48/oauth-google)
* [`luuhai48/oauth-linkedin`](https://github.com/luuhai48/oauth-linkedin)
* [`malago/flarum-linkpreview`](https://github.com/malago86/flarum-linkpreview)
* [`reflar/level-ranks`](https://github.com/ReFlar/level-ranks)
* `reflar-recache`
* [`saleksin/flarum-auth-google`](https://github.com/saleksin/flarum-auth-google)
* [`serakoi/flarumdiscordtheme`](https://github.com/Serakoi/flarum-discord-theme-2)
* [`shriker/flarum-pronouns`](https://github.com/shriker/flarum-pronouns)
* [`simonxeko/follow-users`](https://github.com/simonxeko/follow-users)
* [`simonxeko/preview-discussion`](https://github.com/simonxeko/flarum-ext-preview-discussion)
* [`squeevee/flarum-ext-fancybox`](https://github.com/squeevee/flarum-ext-fancybox)
* [`sycho/flarum-action-log`](https://github.com/SychO9/flarum-action-log)
* [`tank/perspective`](https://github.com/flarum-tank/flarum-perspective)
* [`the-turk/flarum-ext-fancybox`](https://github.com/the-turk/flarum-ext-fancybox)
* [`the-turk/flarum-stargazing-theme`](https://github.com/the-turk/flarum-stargazing-theme)
* [`therealsujitk/flarum-ext-hljs`](https://github.com/therealsujitk/flarum-ext-hljs)
* [`therealsujitk/flarum-ext-show-password`](https://github.com/therealsujitk/flarum-ext-show-password)

All changes: [v3.9.0...v4.0.0](https://github.com/flarum-lang/french/compare/v3.9.0...v4.0.0).

</details>

### CODE REVIEW

**Comment by rob006** [comment]
@Hiobi @qiaeru Just as a note, this is an automated PR generated by bot. The idea is to simplify release process for language pack maintainers - all you need is to approve this pull request and bot will handle the rest. You can read more about the process at forum: https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76 . If you don't want to use this feature, let me know.

**Comment by qiaeru** [comment]
> @Hiobi @qiaeru Just as a note, this is an automated PR generated by bot. The idea is to simplify release process for language pack maintainers - all you need is to approve this pull request and bot will handle the rest. You can read more about the process at forum: https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76 . If you don't want to use this feature, let me know.

Hey @rob006 . This feature seems interesting. We can wait to approve the PR because we want to reach 100% and release a new build after a new Flarum release, but this feature allow us to do that, so that's perfect, thanks.

**Comment by rob006** [comment]
@qiaeru  If you're referring to `4.0.0` as version instead of `3.10.0`, that is because bot detected removal of translations for Formulaire extension, which is technically a BC break. But I can overwrite this if you prefer to continue 3.x line. IMO it is not worth to wait for new Flarum release, the main goal of this feature is to allow maintainers to release more frequently.

**Comment by rob006** [comment]
I actually plan some cleanup of old unused phrases and extensions in main repository, If you plan to release new major release now, I could trigger this cleanup right now, so new release would be without old abandoned extensions and legacy phrases.

**Comment by qiaeru** [comment]
You can tell me when you're done, no emergency here to release something, so take your time. Thanks for the good job!

**Comment by rob006** [comment]
@qiaeru Done, see https://github.com/flarum-lang/french/commit/a9ffec9b5371a5431a167968756e5fe056a523d6 and https://github.com/flarum-lang/french/pull/37

**Review by qiaeru — APPROVED** [review]
Everything seems okay!

**Comment by robbot006** [comment]
Success! Now you can announce new release on [forum](https://discuss.flarum.org/d/615):

~~~markdown
## Version [`v4.0.0`](https://github.com/flarum-lang/french/releases/tag/v4.0.0)

**General changes**:

* Removed outdated Flarum core translations (version `1.3` or higher is supported).


**Added support for new extensions**:

* [`blomstra/fontawesome`](https://github.com/blomstra/flarum-ext-fontawesome)
* [`blomstra/s3-assets`](https://extiverse.com/extension/blomstra/s3-assets)
* [`clarkwinkelmann/flarum-ext-discussion-bookmarks`](https://github.com/clarkwinkelmann/flarum-ext-discussion-bookmarks)
* [`clarkwinkelmann/flarum-ext-ipsum-autocomplete`](https://github.com/clarkwinkelmann/flarum-ext-ipsum-autocomplete)
* [`clarkwinkelmann/flarum-ext-selective-mediaembed`](https://github.com/clarkwinkelmann/flarum-ext-selective-mediaembed)
* [`datlechin/flarum-discussion-overview`](https://github.com/datlechin/flarum-discussion-overview)
* [`ianm/no-meta-title`](https://github.com/imorland/no-meta-title)
* [`justoverclock/best-answer-badge`](https://github.com/justoverclockl/best-answer-badge)
* [`tohsakarat/save-and-load-draft-automatically`](https://github.com/tohsakrat/save-and-load-draft-automatically)
* [`tohsakarat/tags-filter`](https://github.com/tohsakrat/flarum-tags-filter)


**Updated and/or removed outdated translations for extensions**:

* [`askvortsov/flarum-saml`](https://github.com/askvortsov1/flarum-saml)
* [`blomstra/flag-duplicates`](https://github.com/blomstra/flarum-ext-flag-duplicate)
* [`blomstra/payments`](https://extiverse.com/extension/blomstra/payments)
* [`blomstra/realtime`](https://extiverse.com/extension/blomstra/realtime)
* [`clarkwinkelmann/flarum-ext-scout`](https://github.com/clarkwinkelmann/flarum-ext-scout)
* [`datlechin/flarum-birthdays`](https://github.com/datlechin/flarum-birthdays)
* [`flarum/markdown`](https://github.com/flarum/markdown)
* [`flarum/statistics`](https://github.com/flarum/statistics)
* [`fof/analytics`](https://github.com/FriendsOfFlarum/analytics)
* [`fof/best-answer`](https://github.com/FriendsOfFlarum/best-answer)
* [`fof/byobu`](https://github.com/FriendsOfFlarum/byobu)
* [`fof/discussion-language`](https://github.com/FriendsOfFlarum/discussion-language)
* [`fof/filter`](https://github.com/FriendsOfFlarum/filter)
* [`fof/gamification`](https://github.com/FriendsOfFlarum/gamification)
* [`fof/merge-discussions`](https://github.com/FriendsOfFlarum/merge-discussions)
* [`fof/pretty-mail`](https://github.com/FriendsOfFlarum/pretty-mail)
* [`fof/sitemap`](https://github.com/FriendsOfFlarum/sitemap)
* [`fof/stopforumspam`](https://github.com/FriendsOfFlarum/stopforumspam)
* [`fof/subscribed`](https://github.com/FriendsOfFlarum/subscribed)
* [`fof/upload`](https://github.com/FriendsOfFlarum/upload)
* [`ianm/follow-users`](https://github.com/imorland/follow-users)
* [`ianm/level-ranks`](https://github.com/imorland/level-ranks)
* [`ianm/syndication`](https://github.com/imorland/syndication)
* [`ianm/synopsis`](https://github.com/imorland/synopsis)
* [`jslirola/flarum-ext-login2seeplus`](https://github.com/jslirola/flarum-ext-login2seeplus)
* [`justoverclock/discussion-info`](https://github.com/justoverclockl/discussions-info)
* [`justoverclock/last-registered-users`](https://github.com/justoverclockl/last-registered-users)
* [`justoverclock/related-discussions`](https://extiverse.com/extension/justoverclock/related-discussions)
* [`katosdev/signature`](https://github.com/katosdev/signature)
* [`kilowhat/flarum-ext-custom-paths`](https://extiverse.com/extension/kilowhat/flarum-ext-custom-paths)
* [`kilowhat/flarum-ext-rich-embeds`](https://extiverse.com/extension/kilowhat/flarum-ext-rich-embeds)
* [`michaelbelgium/mybb-to-flarum`](https://github.com/MichaelBelgium/mybb_to_flarum)
* [`michaelbelgium/flarum-profile-views`](https://github.com/MichaelBelgium/flarum-profile-views)
* [`migratetoflarum/fake-data`](https://github.com/migratetoflarum/fake-data)
* [`nearata/flarum-ext-embed-video`](https://github.com/Nearata/flarum-ext-embed-video)
* [`nearata/flarum-ext-minecraft-avatars`](https://github.com/Nearata/flarum-ext-minecraft-avatars)
* [`nearata/flarum-ext-tags-color-generator`](https://github.com/Nearata/flarum-ext-tags-color-generator)
* [`nearata/flarum-ext-twofactor`](https://github.com/Nearata/flarum-ext-twofactor)
* [`the-turk/flarum-mathren`](https://github.com/the-turk/flarum-mathren)
* [`the-turk/flarum-regrole`](https://github.com/the-turk/flarum-regrole)
* [`the-turk/flarum-stickiest`](https://github.com/the-turk/flarum-stickiest)
* [`therealsujitk/flarum-ext-gifs`](https://github.com/therealsujitk/flarum-ext-gifs)
* [`zerosonesfun/flarum-bbcode-button`](https://github.com/zerosonesfun/flarum-bbcode-button)


**Removed support for outdated extensions**:

* [`amaurycarrade/flarum-ext-syndication`](https://github.com/AmauryCarrade/flarum-ext-syndication)
* [`andre-pullinen/ads`](https://github.com/andre-pullinen/ads)
* [`antoinefr/flarum-ext-money`](https://github.com/AntoineFr/flarum-ext-money)
* [`antoinefr/flarum-ext-online`](https://github.com/AntoineFr/flarum-ext-online)
* [`askvortsov/flarum-auth-sync`](https://github.com/askvortsov1/flarum-auth-sync)
* [`clarkwinkelmann/flarum-ext-bookmarks`](https://github.com/clarkwinkelmann/flarum-ext-bookmarks)
* [`clarkwinkelmann/flarum-ext-email-as-display-name`](https://github.com/clarkwinkelmann/flarum-ext-email-as-display-name)
* [`clarkwinkelmann/flarum-ext-emojionearea`](https://github.com/clarkwinkelmann/flarum-ext-emojionearea)
* [`clarkwinkelmann/flarum-ext-manual-discussion-slug`](https://github.com/clarkwinkelmann/flarum-ext-manual-discussion-slug)
* [`clarkwinkelmann/flarum-ext-quiz-polls`](https://github.com/clarkwinkelmann/flarum-ext-quiz-polls)
* [`datitisev/flarum-ext-dashboard`](https://github.com/datitisev/flarum-ext-dashboard)
* `flarumi-oauth-vkontakte`
* `flarumi-oauth-yandex`
* [`fof/transliterator`](https://github.com/FriendsOfFlarum/transliterator)
* [`ianm/flarum-diff`](https://github.com/imorland/flarum-diff)
* [`ianm/flarum-regrole`](https://github.com/imorland/flarum-regrole)
* `justoverclock-discussion-sentiment-analyzer`
* [`justoverclock/image-gallery`](https://github.com/justoverclockl/image-gallery)
* [`justoverclock/flarum-ext-readmore`](https://github.com/justoverclockl/flarum-ext-readmore)
* [`kilowhat/flarum-ext-formulaire`](https://extiverse.com/extension/kilowhat/flarum-ext-formulaire)
* [`kvothe/reply-to-see`](https://github.com/oaklinq/flarum-ext-reply2see)
* [`kyrne/aegis`](https://extiverse.com/extension/kyrne/aegis)
* [`kyrne/shout`](https://github.com/KyrneDev/Shout-public)
* [`luuhai48/oauth-google`](https://github.com/luuhai48/oauth-google)
* [`luuhai48/oauth-linkedin`](https://github.com/luuhai48/oauth-linkedin)
* [`malago/flarum-linkpreview`](https://github.com/malago86/flarum-linkpreview)
* [`reflar/level-ranks`](https://github.com/ReFlar/level-ranks)
* `reflar-recache`
* [`saleksin/flarum-auth-google`](https://github.com/saleksin/flarum-auth-google)
* [`serakoi/flarumdiscordtheme`](https://github.com/Serakoi/flarum-discord-theme-2)
* [`shriker/flarum-pronouns`](https://github.com/shriker/flarum-pronouns)
* [`simonxeko/follow-users`](https://github.com/simonxeko/follow-users)
* [`simonxeko/preview-discussion`](https://github.com/simonxeko/flarum-ext-preview-discussion)
* [`squeevee/flarum-ext-fancybox`](https://github.com/squeevee/flarum-ext-fancybox)
* [`sycho/flarum-action-log`](https://github.com/SychO9/flarum-action-log)
* [`tank/perspective`](https://github.com/flarum-tank/flarum-perspective)
* [`the-turk/flarum-ext-fancybox`](https://github.com/the-turk/flarum-ext-fancybox)
* [`the-turk/flarum-stargazing-theme`](https://github.com/the-turk/flarum-stargazing-theme)
* [`therealsujitk/flarum-ext-hljs`](https://github.com/therealsujitk/flarum-ext-hljs)
* [`therealsujitk/flarum-ext-show-password`](https://github.com/therealsujitk/flarum-ext-show-password)



All changes: [v3.9.0...v4.0.0](https://github.com/flarum-lang/french/compare/v3.9.0...v4.0.0).

In order to update run these commands:

```console
composer require flarum-lang/french
php flarum cache:clear
```


**This version removes support for older versions of Flarum and some outdated extensions. Before updating make sure you're using the most recent versions of Flarum and extensions.**


~~~

**Pull request merged**
